name: Build and Deploy API Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    enviroment:
     name: testing
    env:
     ENV_STATE: test 
     DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
     DATABASE_PORT: ${{DATABASE_PORT}}
     DATABASE_USERNAME: ${{DATABASE_USERNAME}}
     DATABASE_NAME: ${{DATABASE_NAME}}
     DATABASE_URL: ${{DATABASE_URL}}
     SECRET_KEY: ${{SECRET_KEY}}
     ALGORITHM: ${{ALGORITHM}}
     ACCESS_TOKEN_EXPIRE_MINUTES:  ${{ACCESS_TOKEN_EXPIRE_MINUTES}}
     DB_FORCE_ROLL_BACK: ${{DB_FORCE_ROLL_BACK}}
     TEST_DATABASE_URL: ${{TEST_DATABASE_URL}}
     TEST_DB_FORCE_ROLL_BACK: ${{TEST_DB_FORCE_ROLL_BACK}}
     TEST_DEBUG: ${{TEST_DEBUG}}
     TEST_SECRET_KEY: ${{TEST_SECRET_KEY}}
     TEST_ALGORITHM: ${{TEST_ALGORITHM}}
     TEST_ACCESS_TOKEN_EXPIRE_MINUTES: ${{TEST_ACCESS_TOKEN_EXPIRE_MINUTES}}
    steps:
     - name: Pulling git repo
       uses: actions/checkout@v5
     - name: Install Python Version 3.13 
       uses: actions/setup-python@v6 
       with:
         python-version: '3.13'
     - name: Update Pip 
       run: python -m pip install --upgrade pip 
     - name: Install Dependencies 
       run: pip install -r requirements.txt 
     - name: Testing with Pytest 
       run: |
         pip install pytest 
         pytest 