name: Build and Deploy API Code

on:
  push:
    branches:
      - main

jobs:
  build:
     env:
      ENV_STATE:test
      DATABASE_HOSTNAME:localhost
      DATABASE_PORT:5432
      DATABASE_USERNAME:postgres
      DATABASE_PASSWORD:$#@dowStorm#,1
      DATABASE_NAME:fastapi
      DATABASE_URL:postgresql://postgres:%24%23%40dowStorm%23%2C1@localhost:5432/fastapi
      SECRET_KEY:09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM:HS256
      ACCESS_TOKEN_EXPIRE_MINUTES:120
      DB_FORCE_ROLL_BACK:False
      TEST_DATABASE_URL:sqlite:///test.db
      TEST_DB_FORCE_ROLL_BACK:True
      TEST_DEBUG:True
      TEST_SECRET_KEY:testsecret
      TEST_ALGORITHM:HS256
      TEST_ACCESS_TOKEN_EXPIRE_MINUTES:5
     runs-on: ubuntu-latest
   
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v5
      - name: Install Python Version 3.13 
        uses: actions/setup-python@v6 
        with:
          python-version: '3.13'
      - name: Update Pip 
        run: python -m pip install --upgrade pip 
      - name: Install Dependencies 
        run: pip install -r requirements.txt 
      - name: Testing with Pytest 
        run: |
          pip install pytest 
          pytest 