name: Build and Deploy API Code 
on: 
  push: 
    branches: 
      - "main"
      - "production"

jobs:
  job1:
  runs-on: ubuntu-latest
  steps:
    - name: pulling git repo
    - uses: actions/checkout@v5

  
      

  